## Fixed and Learnable hyper-parameters 
---
  epochs: 3
  use_labels: true
  bert_model_name: bert_12_768_12
  bert_dataset: book_corpus_wiki_en_uncased
  latent_distribution: [{dist_type: vmf, kappa: {range: [20.0, 80.0]}}]
  max_seq_len: {i_range: [128]}
  gamma: {i_range: [10, 20], step: 10}
  lr: {range: [1e-5, 1e-4]}
  decoder_lr: {range: [0.0001, 0.002]}
  n_latent: {i_range: [20]}
  optimizer: [bertadam]
  warmup_ratio: {range: [0.05, 0.2]}
  batch_size: {i_range: [16]}
  classifier_dropout: 0.2
    