# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish Python Package Release

on:
  release:
    types: [created]

jobs:
  pypi-publish:

    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/tmnt
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.TMNT_API_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TMNT_API_KEY }}
        RELEASE: 1
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
